### ISSUE TITLE
98-PY/exit-code-1073741510

### ISSUE THREAD

**Issue by Paurikova2** [dataquest-dev/dspace-python-api#10] opened 2023-05-04 06:51 UTC
Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)

After sunning dspace migratin for some time, the migration completes with this exit code. But the data is successfully imported.

**Comment by MajoBerger** [comment] 2023-05-31 12:37
@Paurikova2 was this behaviour observed again? This exit code means manual stopping of python (Ctrl + C or stop button or similar).  If it was not observed again, we can just close this issue.

**Comment by MajoBerger** [comment] 2023-05-31 12:55
supposedly caused by Pycharm, according to @milanmajchrak

**Closed by MajoBerger** 2023-05-31 12:55 UTC
